import { StructuredSummary } from './types';

import { storageLayer } from '../../storage';

/**
 * Generates a structured Markdown transfer summary matching Architecture §10.3.
 * This is designed to be pasted into a new AI conversation to restore context.
 */
export async function generateTransferTemplate(summary: StructuredSummary): Promise<string> {
  const state = await storageLayer.appState.getValue();
  const platform = state.platform || 'Unknown';
  const platformName =
    platform === 'chatgpt'
      ? 'ChatGPT'
      : platform === 'claude'
        ? 'Claude'
        : platform === 'gemini'
          ? 'Gemini'
          : platform;
  const turns = state.stats.turns;
  const totalTokens = state.tokenEstimate.count;
  const now = new Date();
  const timestamp = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

  let md = `## Context Transfer Summary\n`;
  md += `**Generated by AI Context Tracker**\n`;
  md += `**Source:** ${platformName} | **Conversation Length:** ${turns} turns | ~${totalTokens.toLocaleString()} tokens\n`;
  md += `**Generated:** ${timestamp}\n\n`;

  // --- Project Goal ---
  if (summary.projectGoal) {
    md += `### Project Goal\n`;
    md += `${summary.projectGoal}\n\n`;
  }

  // --- Key Topics Discussed ---
  if (summary.rankedSentences && summary.rankedSentences.length > 0) {
    md += `### Key Topics Discussed\n`;
    summary.rankedSentences.slice(0, 5).forEach((sentence, idx) => {
      md += `${idx + 1}. ${sentence}\n`;
    });
    md += '\n';
  }

  // --- Important Decisions Made ---
  if (summary.architectureDecisions.length > 0) {
    md += `### Important Decisions Made\n`;
    summary.architectureDecisions.forEach((decision) => {
      md += `- ${decision}\n`;
    });
    md += '\n';
  }

  // --- Current State ---
  if (summary.currentDiscussion) {
    md += `### Current State\n`;
    md += `${summary.currentDiscussion}\n\n`;
  }

  // --- Key Code/Artifacts Referenced ---
  if (summary.filesCreated.length > 0 || summary.codeGenerated) {
    md += `### Key Code/Artifacts Referenced\n`;
    if (summary.filesCreated.length > 0) {
      summary.filesCreated.slice(0, 15).forEach((file) => {
        md += `- \`${file}\`\n`;
      });
    }
    if (summary.codeGenerated && summary.filesCreated.length === 0) {
      md += `- Code was generated during this conversation\n`;
    }
    md += '\n';
  }

  // --- Bugs / Issues ---
  if (summary.bugs.length > 0) {
    md += `### Known Issues\n`;
    summary.bugs.slice(0, 5).forEach((bug) => {
      md += `- ${bug}\n`;
    });
    md += '\n';
  }

  // --- Pending Tasks ---
  if (summary.pendingTasks.length > 0) {
    md += `### Pending Tasks\n`;
    summary.pendingTasks.forEach((task) => {
      md += `- [ ] ${task}\n`;
    });
    md += '\n';
  }

  // --- User Preferences ---
  if (summary.userPreferences.length > 0) {
    md += `### User Preferences\n`;
    summary.userPreferences.forEach((pref) => {
      md += `- ${pref}\n`;
    });
    md += '\n';
  }

  // --- APIs & Services ---
  if (summary.apis.length > 0) {
    md += `### APIs & Services Used\n`;
    md +=
      summary.apis
        .slice(0, 10)
        .map((a) => `\`${a}\``)
        .join(', ') + '\n\n';
  }

  // --- Instructions for Continuation ---
  md += `### Instructions for Continuation\n`;
  md += `Please continue this conversation. The key context is above.\n`;
  if (summary.currentDiscussion) {
    md += `Focus on: ${summary.currentDiscussion.split(' → ').pop() || 'the current task'}\n`;
  } else if (summary.projectGoal) {
    md += `Focus on: ${summary.projectGoal}\n`;
  }

  return md;
}
